143 unrelevant devices get deleted by cb delete entity
RWTH-EBC/FiLiP pull request #144
Opened 2022-05-09 07:01 UTC by djs0109

Since the IoTAgent API does not provide filter functionality, I implement this in the IoTAgentClient of FiLiP. In this way the function get_device_list( ) can now return the devices filtered by entity_id.

2022-05-10 09:11 UTC, tstorek requested changes
Thanks for the contribution. only small remakrs :)

2022-05-10 13:36 UTC, djs0109 commented on filip/clients/ngsi_v2/iota.py
> +    def filter_device_list(devices: List[Device],
Yes good point, then this function can also be invoked more simply by other modules

2022-05-10 14:05 UTC, djs0109 commented on tests/clients/test_ngsi_v2_cb.py
> +        while True:
Done. 926ee6ef6a32a045a0ca684e595ab3b3d9531f35

2022-05-10 14:06 UTC, djs0109 commented on tests/clients/test_ngsi_v2_cb.py
> +        n_devices = 20
see above.

2022-05-10 14:06 UTC, djs0109 commented on tests/clients/test_ngsi_v2_cb.py
> +            n_devices += -1
see above.

2022-05-10 14:06 UTC, djs0109 commented on tests/clients/test_ngsi_v2_cb.py
> +            self.assertEqual(len(self.iotac.get_device_list()), n_devices)
see above.

2022-06-29 13:20 UTC, tstorek commented
@djs0109 I made some minor modifications and added some more tests. Please double-check if everything works as expected.

2022-06-30 09:17 UTC, djs0109 commented
LGTM

2022-06-30 19:25 UTC, merged

2022-06-30 19:27 UTC, tstorek commented
@djs0109 thank you very much!