Add new QL endpoints of /v2/attr and /v2/attr/{attr_name}
RWTH-EBC/FiLiP pull request #16
Opened 2021-08-29 05:51 UTC by orange95

2021-09-09 11:20 UTC, tstorek requested changes
@orange95 thanks, for this pull request. Unfortunatly, there are no tests provided for the functionality. Please, do so. Additionally, it would great if you state why you deviate from the TimeSeries pattern. I think, that all queries that actually contain values should be converted to Either TimeSeries objects or to list of TimeSeriesObjects

2021-09-22 11:04 UTC, orange95 commented
as for adding test, I plan to add these to the line 126 of tests/clients/test_ngsi_v2_timeseries.py
now need to pull in order to commit to another issue, so I put the code here

`            entity_attr = client.get_entity_by_attrs(
                entity_type=self.entity_1.type)
            for entity in entity_attr:
                print(entity.to_pandas())

            entity_attr_name = client.get_entity_by_attr_name(
                attr_name="temperature", entity_type=self.entity_1.type)
            for entity in entity_attr_name:
                print(entity.to_pandas())


`

2022-07-06 19:49 UTC, tstorek commented
@SBlechmann is there still any progress on this?

2022-07-07 10:41 UTC, SBlechmann commented
Yes, we are still on it, sorry for the delay.

2024-05-08 09:46 UTC, SystemsPurge commented
@tstorek First , appologies for the long list of commits, only the last three are relevant, the rest stems from a rebase on master because the branch was old. The methods now return the sought after timeseries/timeseries list object. I could not find a way to avoid nested loops, given that the response itself comprises of nested/categorized elements. 
One important detail : The get_entity_by_attrs method does not combine the timeseries of same entities for different attributes, since extending the values/index for different attributes doesnt seem to be a trivial task : If done properly, the timestamps in the indexes should be compared one by one, to determine whether adding a None value for a specific attribute is necessary. 
Hence why in the test, as u can see, the method now returns a timeseries list of size : number of unique entities x number of unique attributes. The question then becomes, is it ok for this method to return such a result OR, should a timeseries method be implemented, that combines timeseries of same entities with different attributes?

2024-05-22 12:53 UTC, djs0109 requested changes

2024-05-23 07:39 UTC, SystemsPurge commented on filip/clients/ngsi_v2/quantumleap.py
> +        return [TimeSeries(index=item.get('index'),
Could you please give me more information on how to reproduce this ? What versions of the GEs are you running ? Did this error come up in the unittests ?
 I've just re-ran the tests ( with added types to account for that scenario ) and it still works for me.
![grafik](https://github.com/RWTH-EBC/FiLiP/assets/126253836/2ef9968f-52ed-42a8-8d30-672cf2d1bc61)

![grafik](https://github.com/RWTH-EBC/FiLiP/assets/126253836/b01b2752-0b7f-418a-8106-b93e7cb06b25)

2024-06-18 08:34 UTC, djs0109 approved these changes

2024-06-18 13:53 UTC, djs0109 approved these changes

2024-06-18 13:57 UTC, merged