fix: bug in typePattern validation
RWTH-EBC/FiLiP pull request #180
Opened 2022-12-09 09:34 UTC by richardmarston

Changed the line as proposed in the issue definition.

2022-12-19 13:04 UTC, tstorek requested changes
@richardmarston thank your very much. Could you please add a little test_case for this :) Thanks

2022-12-19 13:38 UTC, richardmarston commented
I have written a Dockerfile that runs tests/utils/test_filter.py. The output is this:

```
 {
  "LOG_LEVEL": "ERROR",
  "CB_URL": "http://localhost:1026",
  "IOTA_URL": "http://localhost:4041",
  "IOTA_JSON_URL": "http://localhost:4041",
  "IOTA_UL_URL": "http://127.0.0.1:4061",
  "QL_URL": "http://127.0.0.1:8668",
  "MQTT_BROKER_URL": "mqtt://127.0.0.1:1883",
  "CI_JOB_ID": null,
  "FIWARE_SERVICE": "filip",
  "FIWARE_SERVICEPATH": "/41f4e71481164dd08bba18aa136c0a3f"
}

```
 - Does this output indicate that the tests have been run correctly?
 - Should I add the test case to test_filter.py?

2022-12-19 13:56 UTC, tstorek commented
@richardmarston ideally, your test should be located in the model section of the tests. If you have your own FIWARE instance running you can simple use your local instance:

1. Copy and rename the tests/TEMPLATE_ENV file to .env (don't commit that file)
2. Fill in all your parameters
3. Run the tests on your local machine. Filip will then automatically search for the .env file.
4. Commit your test. This will trigger our pipeline and run the tests with our server instance. As you can see above.

Please, contact me directly if you require help with the testing instance.

2023-02-14 13:56 UTC, sbanoeon approved these changes

2023-02-17 15:53 UTC, merged