feat: add messages to all KeyErrors
RWTH-EBC/FiLiP pull request #192
Opened 2023-05-30 08:26 UTC by FWuellhorst

Closes #191

2023-05-30 13:58 UTC, djs0109 requested changes

2023-05-30 14:44 UTC, FWuellhorst commented on filip/semantics/semantics_models.py
> +            raise KeyError(f"v is neither of type SemanticIndividual nor SemanticClass but {v}")
good point, I used type(v)

2023-05-30 15:53 UTC, djs0109 approved these changes

2023-05-31 06:47 UTC, FWuellhorst commented
Also the CI works again

2023-05-31 06:47 UTC, merged