Changed all Regexes to disallow spaces
RWTH-EBC/FiLiP pull request #20
Opened 2021-09-08 08:33 UTC by RedingJeff

Now the fields are really FIWARE safe. 

In two cases I shortened the regex, but as far as I saw (and the text stateted) these limitations were not needed for these fields. * is an allowed char.

2021-09-09 10:19 UTC, tstorek requested changes
@RedingJeff 
Thanks for the pull request. Maybe this would be also a great opportunity to introduce a test for this to the changed models. Don't you think?

I think that * is part of the regex expression. Please, double check on e.g. https://www.regexpal.com/

2021-09-09 13:31 UTC, RedingJeff commented
I added tests for all the fields. 
To reduce the redundancy and improve maintainability, I grouped the two FiwareRegexes in a class togehter

I checked the simple regex again, the "*" is not needed, but the regex that should prevent specific strings was not correct. I corrected it.

2021-09-10 07:28 UTC, tstorek requested changes
Hi. Looks good. Please raise the version number by a minor release and write a small changelog comment as Bugfix. Easiest way is to search the project files for the current version number and and then adjust it :)

2021-09-10 07:28 UTC, tstorek commented on filip/models/base.py
> +
Almost there. Maybe we can use annotated enum here. Hence, we would alogn it with the other enums used in the library.

2021-09-13 13:57 UTC, merged