docs: add committing style guide and fix typos (#244)
RWTH-EBC/FiLiP pull request #246
Opened 2024-02-20 11:52 UTC by WaltherTrgovac

I have added the link for the committing style guide and fixed some typos.

2024-03-06 11:42 UTC, tstorek commented
@WaltherTrgovac I just recognized  that you changed, e.g. `devive` to 'device' in the example. This actually on perpose to highlight it when converting to markdown.

2024-03-07 15:18 UTC, tstorek commented
> I see what you mean, but .md and .py are two separate files, so the .md file stays unchanged. But if you want, I can revert the changes. Besides that, my idea was to make all the #ToDo comment sections and therefore .md files written in full sentences. And other comments I would leave as they are.

That's totally correct. However, we used to have a parser to generate the *.md from *.py. Not sure if it still exists ;)

2024-03-07 15:21 UTC, WaltherTrgovac commented
I assumed that so I think it is better to leave them as it was, I will revert the changes.

2024-03-19 16:02 UTC, Maghnie requested changes
Thanks for the updates!

2024-03-19 16:02 UTC, Maghnie commented on CONTRIBUTING.md
>  - See the [unittest-documentation](https://docs.python.org/3/library/unittest.html#organizing-tests) for further information
```suggestion
- See the [unittest-documentation](https://docs.python.org/3/library/unittest.html#organizing-tests) for further information.
```

2024-04-23 12:23 UTC, djs0109 approved these changes

2024-04-23 12:24 UTC, djs0109 commented
@Maghnie It looks good to me. You can merge if it also looks good for you now :)

2024-04-23 13:13 UTC, Maghnie approved these changes

2024-04-23 13:15 UTC, merged