237 update and refactor examples
RWTH-EBC/FiLiP pull request #278
Opened 2024-04-30 15:08 UTC by WaltherTrgovac

Closes #237.
## Current state of `examples\ngsiv2` that have been worked on:

- `e01_ngsi_v2_context_basics.py`: working :white_check_mark: _(last checked: 24.04.2024)_
- `e02_ngsi_v2_context_relationships.py`: working :white_check_mark: _(last checked: 24.04.2024)_
- `e03_ngsi_v2_context_subscriptions_http.py`: working :white_check_mark: _(last checked: 24.04.2024)_
- `e04_ngsi_v2_context_subscriptions_mqtt.py`: working :white_check_mark: _(last checked: 24.04.2024)_
  - Changes: fixed deprecated methods
- `e05_ngsi_v2_context_registrations.py`: working :white_check_mark: _(last checked: 30.04.2024)_
  - Changes: fixed deprecated methods, PEP-8 errors, and reformatted comments
- `e06_ngsi_v2_autogenerate_context_data_models.py`: not working :x: _(last checked: 30.04.2024)_
  - Notes: A very short example, but half of the code is deprecated, maybe it should be completely remade?
- `e07_ngsi_v2_iota_basics.py`: not completely working :warning: _(last checked: 30.04.2024)_
  - Changes: fixed deprecated methods
  - Notes: The code gets executed, but with one small error from logger: `2024-04-30 17:03:55,412 filip.clients.ngsi_v2.cb.ContextBrokerClient ERROR: Could not delete attribute 'on' of entity'sensor2'  
 Reason: {"error":"NotFound","description":"The requested entity has not been found. Check type and id"}`

2024-06-12 14:52 UTC, Maghnie requested changes
Thanks for the extensive initial updates!

2024-06-12 14:52 UTC, Maghnie commented on examples/ngsi_v2/e08_ngsi_v2_iota_paho_mqtt.py
For some unknown reason, this example doesn't work for me. The temperature and humidity values are “null” after all the for-loop iterations.

2024-06-12 14:52 UTC, Maghnie commented on examples/ngsi_v2/e09_ngsi_v2_iota_filip_mqtt.py
This example still produces warnings. Can they be avoided?

2024-06-12 14:52 UTC, Maghnie commented on examples/ngsi_v2/e10_ngsi_v2_quantumleap.py
There are many nested quotation marks of the same type here.

2024-06-18 11:37 UTC, WaltherTrgovac commented on examples/ngsi_v2/e01_ngsi_v2_context_basics.py
> +        logger.info(f"Context broker version: {value["version"]} at url: "
Fixed. Python version 3.9 does not allow nested quotation marks of the same type. Now every example can also be executed in Python 3.9.

2024-06-18 11:40 UTC, WaltherTrgovac commented on examples/basics/e01_http_clients.py
I think it does actually read it, because if you try to change something in the env file, you will get errors in the example.

2024-06-18 11:40 UTC, WaltherTrgovac commented on examples/ngsi_v2/e10_ngsi_v2_quantumleap.py
Fixed.

2024-06-18 12:21 UTC, WaltherTrgovac commented on examples/ngsi_v2/e09_ngsi_v2_iota_filip_mqtt.py
This is happening due to the nature of the example. We could just comment out the part that is producing the error. This is the part 3.2 in this case, but I think the point of the example is to show the methods and not an actual real case usage, but I am not sure.

2024-06-25 12:52 UTC, djs0109 requested changes
Now there is some problem with the reading of `.env.filip` . It seems like the variables will only be correctly loaded when the `.env.filip` is put under the path of the examples, i.e. `examples/ngsi_v2/` or `examples/basics/` @WaltherTrgovac could you have a look on that? If necessary you can modify the `filip/config.py`, where the variables are loaded

2024-07-02 13:22 UTC, Maghnie commented
> Now there is some problem with the reading of `.env.filip` . It seems like the variables will only be correctly loaded when the `.env.filip` is put under the path of the examples, i.e. `examples/ngsi_v2/` or `examples/basics/` @WaltherTrgovac could you have a look on that? If necessary you can modify the `filip/config.py`, where the variables are loaded

Wasn't it always like that? I think in the config of filip it says that the env file should be in the working directory, so it's up to the user to take care of that.

2024-07-03 11:03 UTC, WaltherTrgovac commented
> Now there is some problem with the reading of `.env.filip` . It seems like the variables will only be correctly loaded when the `.env.filip` is put under the path of the examples, i.e. `examples/ngsi_v2/` or `examples/basics/` @WaltherTrgovac could you have a look on that? If necessary you can modify the `filip/config.py`, where the variables are loaded

If I am understanding this correctly, the method `SettingsConfigDict` in the class `Settings` is taking the path of the `.env.filip` file. It was set so that it is found only when the files to execute are in the same directory as the `.env.filip`. 
I have now adjusted that path so that the file can be located anywhere in the repository. I use the glob python package for that. First I locate the path of the repository with GitPython package and use that as the root directory. Then I look through the whole repository for the `.env.filip` file. The problem is that the `.env.filip` is a hidden file and glob package supports searching for hidden files only from the Python version 3.11... 😞. If somebody knows a solution for the earlier versions of Python that would be great.
And another thing, I have no idea how to test this implementation, I have just tested it manually...

2024-07-09 11:58 UTC, djs0109 commented
> If somebody knows a solution for the earlier versions of Python that would be great.

Never mind, I have changed it now

2024-07-09 12:14 UTC, Maghnie commented
> > If somebody knows a solution for the earlier versions of Python that would be great.
> 
> Never mind, I have changed it now

Then to avoid confusion between multiple env files, we should probably remove the copy under [basics](https://github.com/RWTH-EBC/FiLiP/tree/237-update-and-refactor-examples/examples/basics). Or do you see another use for it?

2024-07-09 12:19 UTC, djs0109 commented
Nice hint. No we don't need it any longer

2024-07-09 12:55 UTC, Maghnie approved these changes

2024-07-09 13:31 UTC, djs0109 commented
Now only e6 cannot work, because the code regarding data model creation is not yet migrated to pydantic V2

2024-07-09 13:31 UTC, djs0109 approved these changes

2024-07-09 14:37 UTC, merged