288 filip support right now only paylaod in mqtt custom / http custom but orion already supports json and ngsi as further options
RWTH-EBC/FiLiP pull request #296
Opened 2024-07-01 09:20 UTC by SystemsPurge

The following warning pops up "UserWarning: Field name "json" shadows an attribute in parent "Mqtt"" ( due to the json fields in MqttCustom and HttpCustom ). Since the Http/Mqtt models do not have an explicit json field, i take it this is coming from some field/property in the base model.
Tried to circumvent the warning by the use of aliases which obviously did not work.

Not sure what model to specify for the json payload type, i just put a Dict[str, any] for now ( despite number/string being valid json , the orion manual specifies that it needs to be a JSON object and not an object of primitive type )

Any input on these two points is welcome.

2024-07-02 08:44 UTC, djs0109 requested changes

2024-07-02 08:44 UTC, djs0109 commented on tests/models/test_ngsi_v2_subscriptions.py
Could you please also add tests that send at least 3 subscriptions (payload, json, ngsi) to Orion endpoints and then validate them by querying the created subcriptions from Orion? The idea is to make sure the created data models are also valid for Orion

2024-07-09 06:39 UTC, djs0109 commented
closes #288

2024-07-09 07:03 UTC, djs0109 commented
I think it would be great if we can test the functionality of these fields too. Could you please implement a test that uses `json`, `ngsi`, `payload` for `mqttCustom`? An example can be found here https://github.com/RWTH-EBC/FiLiP/blob/7919664cad1d7ff3800724f819a7c9f43bd28a80/tests/clients/test_ngsi_v2_cb.py#L832

2024-07-12 13:24 UTC, RCX112 commented
> The following warning pops up "UserWarning: Field name "json" shadows an attribute in parent "Mqtt"" ( due to the json fields in MqttCustom and HttpCustom ). Since the Http/Mqtt models do not have an explicit json field, i take it this is coming from some field/property in the base model. Tried to circumvent the warning by the use of aliases which obviously did not work.
> 
> Not sure what model to specify for the json payload type, i just put a Dict[str, any] for now ( despite number/string being valid json , the orion manual specifies that it needs to be a JSON object and not an object of primitive type )
> 
> Any input on these two points is welcome.

@SystemsPurge When I implemented the HttpCustom model I also had the same warnings. I simply supressed them with the warnings library, because the json() method of pydantic is already outdated anyway:

```
import warnings

# The pydantic models still have a .json() function, but this method is deprecated.
warnings.filterwarnings("ignore", category=UserWarning,
                        message='Field name "json" shadows an attribute in parent "Http"')
warnings.filterwarnings("ignore", category=UserWarning,
                        message='Field name "json" shadows an attribute in parent "Mqtt"')
```

2024-07-15 09:27 UTC, RCX112 commented
@djs0109 Which version of Orion do we currently use for the tests, because the custom notifications don't work for version 3.7 for example?

2024-07-17 12:56 UTC, djs0109 commented
Hi @RCX112 , it should be >= 3.8

2024-07-17 13:04 UTC, djs0109 approved these changes
@SystemsPurge @RCX112 LGTM, thank you!

2024-07-17 13:06 UTC, merged