Added query language test for arbitrary q expressions
RWTH-EBC/FiLiP pull request #349
Opened 2024-11-14 15:07 UTC by SystemsPurge

It should be possible to just add a q expression to the self.qs array and test again. In my own setup, expressions starting with '?q=' did not work for some reason. Also, since the examples did not mention a case where we do a mixed attr check, where one has a comparaison operator and the other does not (e.g : q='isParked ; temperature<30'), i did not implement that, as it increases the complexity. Will do if absolutely necessary though.
The test is however able to parse composite expressions with parentheses of a single type (e.g: q='(isParked | isMonitoredBy); address[stree-address.number]' or q= '(temperature >= 59 | humidity < 3); brand == "DeLorean"')

2024-11-19 11:08 UTC, djs0109 requested changes

2024-11-19 11:08 UTC, djs0109 commented on tests/clients/test_ngsi_ld_query.py
> +            'temperature.observedAt >= "2020-12-24T12:00:00Z"',
It seems like the `observedAt` is not generated automatically. @SystemsPurge Can you add exactly this timestamp `"2020-12-24T12:00:00Z"` to the `temperature` of some car entities? And then we can see whether this condition work

2024-11-19 11:11 UTC, djs0109 commented
@SystemsPurge, great implementation! The logic is super clear. I have some minor comments. Some of them might already be fixed by me. Could you have a check again?

2024-11-19 17:43 UTC, SystemsPurge commented on tests/clients/test_ngsi_ld_query.py
> +        self.cam = ContextLDEntity(id=f"{self.base}cam0",type=f"{self.base}cam")
I see, do you know any possible reason why i did not get it?

2024-11-19 17:44 UTC, SystemsPurge commented on tests/clients/test_ngsi_ld_query.py
> +        self.cars = [ContextLDEntity(id=f"{self.base}car0{i}",type=f"{self.base}car") for i in range(0,self.cars_nb-1)]
Thats an arbitrary number, should not intefere

2024-11-20 12:56 UTC, djs0109 commented on tests/clients/test_ngsi_ld_query.py
> +        self.cam = ContextLDEntity(id=f"{self.base}cam0",type=f"{self.base}cam")
Maybe it is because of the `--experimental` flag. But anyway, if we first create these objects here, it should be all fine.

2024-11-20 13:39 UTC, djs0109 approved these changes

2024-11-20 13:40 UTC, merged