feat: 60 static device attribute metadata type
RWTH-EBC/FiLiP pull request #61
Opened 2021-10-18 12:55 UTC by RedingJeff

The metadata logic of the device attributes is now the same as the logic for the context attributes. 

It is currently code duplication needed (metadata validator, nealry all device attr fileds). What we could do to prevent it -> make BaseAttribute (of iot.py) inherrit from ContextAttribute (context.py). 

The only difference between these two fields are:

- BaseAttribute, has more fields (no problem)
- ContextAttribute has the field "value", and BaseAttribute not (that is a problem).

This solution would merge the currently seperated context and iot worlds, but remove code duplications. Build the following inheritance structure:

- BaseAttribute (new, equals current ContextAttribute without value field)
- ValueAttribute (only has value field)

=> 
- ContextField(BaseAttribute, ValueAttribute)
    - all current children remain unchanged
- IoTaBaseAttribute(BaseAttribute)
    -  DeviceAttribute(IoTaBaseAttribute)
    -  LazyDeviceAttribute(IoTaBaseAttribute)
    -  StaticDeviceAttribute(IoTaBaseAttribute, ValueAttribute)
- DeviceCommand(Basemodel) (unchanged)

2021-11-03 11:20 UTC, RedingJeff commented
I also added the default value None for each model field that had the type Optional but no default value.

Now their is no hint error if the user does not specifies that an optional field gets assigned the value None. Resulting in a clearer user experience

2021-11-12 15:13 UTC, tstorek requested changes
hi, thanks for the pull. only minor remarks

2021-11-12 15:13 UTC, tstorek commented on tests/clients/test_ngsi_v2_cb.py
> +    StaticDeviceAttribute, TransportProtocol
please do long imports in list in vertical order

2021-11-12 15:13 UTC, tstorek commented on tests/models/test_ngsi_v2_iot.py
> +    Device, TransportProtocol, IoTaBaseAttribute
IoTa schould be IoTA. this would correlate to the other class names

2021-11-12 15:13 UTC, tstorek commented on tests/models/test_ngsi_v2_iot.py
> +            self.assertRaises(ValidationError, IoTaBaseAttribute,
usually when you do this using the context protocol is mcuh cleaner.

```python
with self.assertRaises(ValidationError):
    by failing function
```

2021-11-12 15:13 UTC, tstorek commented on tests/models/test_ngsi_v2_iot.py
> +            self.assertRaises(ValidationError, IoTaBaseAttribute,
but i think taht your approach is also valid

2021-11-16 14:37 UTC, tstorek approved these changes

2021-11-16 14:38 UTC, merged